### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by VoyagerPWS**
minor edit to move configuration file into place

### CODE REVIEW

**Comment by cpiker** [comment]
The main install isn't supposed to need the makefile, it's just there for folks (like me) who like and use gnumake quite a bit.  So the make install shouldn't be required.  Though probably recommended.

**Comment by cpiker** [comment]
Hi @VoyagerPWS !  I see you're still making changes to this branch.  Would you prefer that I hold off on a squash merge for a bit?   Thanks for updating the documentation.  It needs work.

**Comment by VoyagerPWS** [comment]
@cpiker Hmmm . . . Apparently comments sent via email don't show up here, so:

Yup, I'm going through the installation step-by-step and trying to update the README.  (I'm making all the changes to the branch for now, which I should have done originally.)

I think I've hit every step now, but

https://spacephysics.org/das/server

returns

Error importing module 'dasflex': No module named '_das2'
sys.path is:
['/space/dasflex/lib/python3.6', '/space/dasflex/lib', '/space/dasflex/bin', '/usr/lib64/python36.zip', '/usr/lib64/python3.6', '/usr/lib64/python3.6/lib-dynload', '/usr/lib64/python3.6/site-packages', '/usr/lib/python3.6/site-packages']

Is it a "_das2" in the Python source that should be "_dasflex" or a configuration issue?

**Comment by cpiker** [comment]
That's fantastic!  Thanks for the help.  At some point I'll get the manylinux docker image setup and build dasFlex packages, but I don't have that today.

Back to the error at hand, can you post your terminal log?  das2py and das2C should be installed into the same PREFIX and N_ARCH as dasFlex.  If they are then the `MODULE_PATH` set automatically in dasflex.conf should pick them up.    

If you don't have a terminal record handy, what is your `MODULE_PATH`  setting from dasflex.conf ?

_das2 is the lower level C code module used by the das2 python module.  It's common for python extensions to split functionality between a low-level C interface and a higher level python-only module.  At least it was before ctypes came along.

**Comment by VoyagerPWS** [comment]
https://ljg.spacephysics.org/dasflex-terminal.txt

[root@thornarg etc]# grep MODULE_PATH /space/dasflex/etc/dasflex.conf
MODULE_PATH = "/space/dasflex/lib:/space/dasflex/lib/python3.6"

**Comment by cpiker** [comment]
From the terminal log it looks like you forgot to:
```bash
export N_ARCH=/
```
Since that's missing, it looks like `_das2.so` was installed to:
```
/space/dasflex/lib/Linux.x86_64/python3.6/_das2.so
```
which isn't on the MODULE_PATH.  The choices are to go back and reinstall das2py, or to add extra items to the module path.  The upcoming PIP package will hopefully make this much easier.

**Pull request merged**
